In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
%cd /content/drive/MyDrive/Colab Notebooks/머신러닝1/조별활동/와인품질분류/data

/content/drive/MyDrive/Colab Notebooks/머신러닝1/조별활동/와인품질분류/data

In [ ]:
train = pd.read_csv('train.csv', index_col=0)
test = pd.read_csv('test.csv', index_col=0)

In [ ]:
test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
index,,,,,,,,,,,,
0,9.0,0.31,0.48,6.60,0.043,11.0,73.0,0.99380,2.90,0.38,11.6,white
1,13.3,0.43,0.58,1.90,0.070,15.0,40.0,1.00040,3.06,0.49,9.0,red
2,6.5,0.28,0.27,5.20,0.040,44.0,179.0,0.99480,3.19,0.69,9.4,white
3,7.2,0.15,0.39,1.80,0.043,21.0,159.0,0.99480,3.52,0.47,10.0,white
4,6.8,0.26,0.26,2.00,0.019,23.5,72.0,0.99041,3.16,0.47,11.8,white
...,...,...,...,...,...,...,...,...,...,...,...,...
995,7.1,0.59,0.02,2.30,0.082,24.0,94.0,0.99744,3.55,0.53,9.7,red
996,8.7,0.15,0.30,1.60,0.046,29.0,130.0,0.99420,3.22,0.38,9.8,white
997,8.8,0.66,0.26,1.70,0.074,4.0,23.0,0.99710,3.15,0.74,9.2,red
998,7.0,0.42,0.19,2.30,0.071,18.0,36.0,0.99476,3.39,0.56,10.9,red
999,8.5,0.21,0.26,9.25,0.034,73.0,142.0,0.99450,3.05,0.37,11.4,white

# 전처리

## label_encoder

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
label_encoder.fit(train['type'])
train['type'] = label_encoder.transform(train['type'])
test['type'] = label_encoder.transform(test['type'])

## 스케일링

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler

In [ ]:
minmax_col_list = ['fixed acidity', 'citric acid' ,'chlorides','free sulfur dioxide','density','pH','sulphates']
robust_col_list = ['volatile acidity' ,'total sulfur dioxide', 'residual sugar','alcohol']

In [ ]:
min_max_scaler = MinMaxScaler()
scaled_train_data = min_max_scaler.fit_transform(train[minmax_col_list])
scaled_test_data = min_max_scaler.transform(test[minmax_col_list])

train[minmax_col_list] = scaled_train_data
test[minmax_col_list] = scaled_test_data

In [ ]:
robust_scaler = RobustScaler()
scaled_train_data = robust_scaler.fit_transform(train[robust_col_list])
scaled_test_data = robust_scaler.transform(test[robust_col_list])

train[robust_col_list] = scaled_train_data
test[robust_col_list] = scaled_test_data

## upsampling

In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:
X = train.drop('quality', axis=1)  # 입력 변수
y = train['quality']  # 타겟 변수

smote = SMOTE(k_neighbors=4)
X_resampled, y_resampled = smote.fit_resample(X, y)


train_resampled = pd.concat([X_resampled, y_resampled], axis=1)
train_resampled

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type,quality
0,0.148760,2.382353,0.036145,0.603175,0.054908,0.027778,-0.441558,0.139001,0.551181,0.123596,-0.055556,1,5
1,0.413223,1.882353,0.084337,-0.095238,0.096506,0.031250,-0.987013,0.188741,0.354331,0.207865,-0.444444,0,5
2,0.338843,-0.470588,0.234940,-0.158730,0.079867,0.069444,0.259740,0.089647,0.244094,0.168539,0.333333,1,5
3,0.264463,-0.470588,0.186747,0.476190,0.061564,0.097222,-0.129870,0.130904,0.409449,0.157303,0.277778,1,6
4,0.330579,0.647059,0.156627,1.031746,0.083195,0.107639,0.779221,0.161751,0.236220,0.117978,0.333333,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16907,0.356767,-0.219701,0.239730,0.416916,0.039412,0.091742,0.190579,0.118757,0.398633,0.141329,0.730246,1,9
16908,0.354204,-0.222920,0.238742,0.392018,0.039291,0.091679,0.194132,0.116489,0.399782,0.141534,0.751525,1,9
16909,0.407980,-0.040683,0.257072,0.998667,0.039875,0.091731,0.004289,0.170069,0.386243,0.147082,0.217086,1,9
16910,0.274652,0.096531,0.210200,0.034527,0.024635,0.147926,0.128982,0.058318,0.425197,0.108758,1.283713,1,9
16911,0.320239,-0.159562,0.288254,0.256277,0.039704,0.101172,-0.023871,0.098629,0.457586,0.118819,1.045214,1,9

# 모델링

## DecisionTree

In [ ]:
y = train_resampled['quality'] #퀄리티 예측해야할거
X = train_resampled.drop('quality', axis=1) #예측해야할거빼고 나머지

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import StratifiedShuffleSplit

In [ ]:
model = DecisionTreeClassifier()

stratified_split = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=42)
# cv_accuracy = []

n_iter = 0
for train_idx, test_idx in stratified_split.split(X, y):
    X_train, X_val = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_val = y.iloc[train_idx], y.iloc[test_idx]

    #모델 학습
    model.fit(X_train, y_train)

y_pred=model.predict(test)

# 제출파일

In [ ]:
submission = pd.read_csv('sample_submission.csv')

In [ ]:
submission

     index  quality
0        0        0
1        1        0
2        2        0
3        3        0
4        4        0
..     ...      ...
995    995        0
996    996        0
997    997        0
998    998        0
999    999        0

[1000 rows x 2 columns]

In [ ]:
submission['quality'] = y_pred

In [ ]:
submission

     index  quality
0        0        5
1        1        4
2        2        5
3        3        5
4        4        7
..     ...      ...
995    995        5
996    996        5
997    997        4
998    998        4
999    999        6

[1000 rows x 2 columns]

In [ ]:
submission.to_csv('procesing_DecisionTree.csv', index=False)